// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: packages/node/epochproof/epochproofproto/message.proto

package epochproofproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//	*Packet_EcSupporters
	//	*Packet_EcSupportersRequest
	Body isPacket_Body `protobuf_oneof:"body"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packages_node_epochproof_epochproofproto_message_proto_rawDescGZIP(), []int{0}
}

func (m *Packet) GetBody() isPacket_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Packet) GetEcSupporters() *ECSupporters {
	if x, ok := x.GetBody().(*Packet_EcSupporters); ok {
		return x.EcSupporters
	}
	return nil
}

func (x *Packet) GetEcSupportersRequest() *ECSupportersRequest {
	if x, ok := x.GetBody().(*Packet_EcSupportersRequest); ok {
		return x.EcSupportersRequest
	}
	return nil
}

type isPacket_Body interface {
	isPacket_Body()
}

type Packet_EcSupporters struct {
	EcSupporters *ECSupporters `protobuf:"bytes,1,opt,name=ecSupporters,proto3,oneof"`
}

type Packet_EcSupportersRequest struct {
	EcSupportersRequest *ECSupportersRequest `protobuf:"bytes,2,opt,name=ecSupportersRequest,proto3,oneof"`
}

func (*Packet_EcSupporters) isPacket_Body() {}

func (*Packet_EcSupportersRequest) isPacket_Body() {}

type ECSupportersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EI int64  `protobuf:"varint,1,opt,name=EI,proto3" json:"EI,omitempty"`
	EC []byte `protobuf:"bytes,2,opt,name=EC,proto3" json:"EC,omitempty"`
}

func (x *ECSupportersRequest) Reset() {
	*x = ECSupportersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECSupportersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECSupportersRequest) ProtoMessage() {}

func (x *ECSupportersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECSupportersRequest.ProtoReflect.Descriptor instead.
func (*ECSupportersRequest) Descriptor() ([]byte, []int) {
	return file_packages_node_epochproof_epochproofproto_message_proto_rawDescGZIP(), []int{1}
}

func (x *ECSupportersRequest) GetEI() int64 {
	if x != nil {
		return x.EI
	}
	return 0
}

func (x *ECSupportersRequest) GetEC() []byte {
	if x != nil {
		return x.EC
	}
	return nil
}

type ECSupporters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EcSupporter []*ECSupporter `protobuf:"bytes,1,rep,name=ecSupporter,proto3" json:"ecSupporter,omitempty"`
}

func (x *ECSupporters) Reset() {
	*x = ECSupporters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECSupporters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECSupporters) ProtoMessage() {}

func (x *ECSupporters) ProtoReflect() protoreflect.Message {
	mi := &file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECSupporters.ProtoReflect.Descriptor instead.
func (*ECSupporters) Descriptor() ([]byte, []int) {
	return file_packages_node_epochproof_epochproofproto_message_proto_rawDescGZIP(), []int{2}
}

func (x *ECSupporters) GetEcSupporter() []*ECSupporter {
	if x != nil {
		return x.EcSupporter
	}
	return nil
}

type ECSupporter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID           []byte `protobuf:"bytes,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Timestamp        uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockContentHash []byte `protobuf:"bytes,3,opt,name=BlockContentHash,proto3" json:"BlockContentHash,omitempty"`
	Signature        []byte `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (x *ECSupporter) Reset() {
	*x = ECSupporter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECSupporter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECSupporter) ProtoMessage() {}

func (x *ECSupporter) ProtoReflect() protoreflect.Message {
	mi := &file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECSupporter.ProtoReflect.Descriptor instead.
func (*ECSupporter) Descriptor() ([]byte, []int) {
	return file_packages_node_epochproof_epochproofproto_message_proto_rawDescGZIP(), []int{3}
}

func (x *ECSupporter) GetNodeID() []byte {
	if x != nil {
		return x.NodeID
	}
	return nil
}

func (x *ECSupporter) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ECSupporter) GetBlockContentHash() []byte {
	if x != nil {
		return x.BlockContentHash
	}
	return nil
}

func (x *ECSupporter) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_packages_node_epochproof_epochproofproto_message_proto protoreflect.FileDescriptor

var file_packages_node_epochproof_epochproofproto_message_proto_rawDesc = []byte{
	0x0a, 0x36, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2f, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x01, 0x0a, 0x06, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x43, 0x0a, 0x0c, 0x65, 0x63, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x70, 0x6f,
	0x63, 0x68, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x43, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x65, 0x63, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x73, 0x12, 0x58, 0x0a, 0x13, 0x65, 0x63, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x70, 0x72,
	0x6f, 0x6f, 0x66, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x43, 0x53, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x13,
	0x65, 0x63, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x35, 0x0a, 0x13, 0x45,
	0x43, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x45, 0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x45, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x45, 0x43, 0x22, 0x4e, 0x0a, 0x0c, 0x45, 0x43, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65,
	0x72, 0x73, 0x12, 0x3e, 0x0a, 0x0b, 0x65, 0x63, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x43, 0x53, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x72, 0x52, 0x0b, 0x65, 0x63, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x45, 0x43, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x10, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x10, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x69, 0x6f, 0x74, 0x61, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x73, 0x68,
	0x69, 0x6d, 0x6d, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6e,
	0x6f, 0x64, 0x65, 0x2f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2f, 0x65,
	0x70, 0x6f, 0x63, 0x68, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packages_node_epochproof_epochproofproto_message_proto_rawDescOnce sync.Once
	file_packages_node_epochproof_epochproofproto_message_proto_rawDescData = file_packages_node_epochproof_epochproofproto_message_proto_rawDesc
)

func file_packages_node_epochproof_epochproofproto_message_proto_rawDescGZIP() []byte {
	file_packages_node_epochproof_epochproofproto_message_proto_rawDescOnce.Do(func() {
		file_packages_node_epochproof_epochproofproto_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_packages_node_epochproof_epochproofproto_message_proto_rawDescData)
	})
	return file_packages_node_epochproof_epochproofproto_message_proto_rawDescData
}

var file_packages_node_epochproof_epochproofproto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packages_node_epochproof_epochproofproto_message_proto_goTypes = []interface{}{
	(*Packet)(nil),              // 0: epochproofproto.Packet
	(*ECSupportersRequest)(nil), // 1: epochproofproto.ECSupportersRequest
	(*ECSupporters)(nil),        // 2: epochproofproto.ECSupporters
	(*ECSupporter)(nil),         // 3: epochproofproto.ECSupporter
}
var file_packages_node_epochproof_epochproofproto_message_proto_depIdxs = []int32{
	2, // 0: epochproofproto.Packet.ecSupporters:type_name -> epochproofproto.ECSupporters
	1, // 1: epochproofproto.Packet.ecSupportersRequest:type_name -> epochproofproto.ECSupportersRequest
	3, // 2: epochproofproto.ECSupporters.ecSupporter:type_name -> epochproofproto.ECSupporter
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_packages_node_epochproof_epochproofproto_message_proto_init() }
func file_packages_node_epochproof_epochproofproto_message_proto_init() {
	if File_packages_node_epochproof_epochproofproto_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECSupportersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECSupporters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECSupporter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_packages_node_epochproof_epochproofproto_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Packet_EcSupporters)(nil),
		(*Packet_EcSupportersRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packages_node_epochproof_epochproofproto_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_node_epochproof_epochproofproto_message_proto_goTypes,
		DependencyIndexes: file_packages_node_epochproof_epochproofproto_message_proto_depIdxs,
		MessageInfos:      file_packages_node_epochproof_epochproofproto_message_proto_msgTypes,
	}.Build()
	File_packages_node_epochproof_epochproofproto_message_proto = out.File
	file_packages_node_epochproof_epochproofproto_message_proto_rawDesc = nil
	file_packages_node_epochproof_epochproofproto_message_proto_goTypes = nil
	file_packages_node_epochproof_epochproofproto_message_proto_depIdxs = nil
}
